name: 버그 제출
description: 버그를 발견하셨다면 여기로 제출해 주세요.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - baekilda
body:

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: 발생 위치
      description: 어느 부분에서 버그가 있었나요?
      placeholder: (예) 웹사이트 관리페이지
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: 버그 설명
      description: 어떤 버그인지 간략히 설명해 주세요.
      placeholder: (예) 새로고침해도 도다 사진이 바뀌지 않아요ㅠㅠ
    validations:
      required: true
  - type: textarea
    id: bug-link
    attributes:
      label: 링크 첨부
      description: 해당 문제가 발생한 링크 / 퀴즈링크가 있다면 알려주세요.
      placeholder: (예) https://doda.app/website-admin
    validations:
      required: false
  - type: textarea
    id: bug-image
    attributes:
      label: 캡쳐 / 화면녹화
      description: 해당 문제가 발생한 화면녹화 / 캡쳐를 첨부해 주세요.
    validations:
      required: true
  - type: checkboxes
    id: is-fixable
    attributes:
      label: 중복 발생 여부
      description: 해당 버그는 중복으로 나타날 수 있나요?
      options:
        - label: 중복적으로 발생합니다.
          required: false
  - type: checkboxes
    id: is-temporary
    attributes:
      label: 간헐적 현상 여부
      description: 해당 버그는 간헐적으로 나타나고 있나요?
      options:
        - label: 간헐적으로 발생합니다.
          required: false
  - type: textarea
    id: bug-repeat
    attributes:
      label: 중복 발생 방법
      description: 해당 버그를 중복으로 나타나게 하는 방법을 자세히 설명해 주세요.
      placeholder: |
        (예)
        1. doda.app 로그인
        2. https://doda.app/website-admin 에 접속
        3. 브라우저 주소 창 옆에 있는 새로고침 버튼 여러 번 누르기
        4. 도다 사진이 바뀌지 않음
    validations:
      required: false
  - type: textarea
    id: console-image
    attributes:
      label: 콘솔 출력 캡쳐
      description: 가능하다면 재발자도구 → 콘솔 캡쳐하고 올려주세요.
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: 버전
      description: 사용 중인 버전을 알려주세요.
      options:
        - 1.2.15 (21/12/21)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: 어떤 브라우저에서 문제가 발생했나요?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: 어떤 운영체제에서 문제가 발생했나요?
      multiple: true
      options:
        - iOS
        - Android
        - macOS
        - Windows
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: 기기 정보
      description: 모바일이었다면, 어떤 장치를 사용하고 있는지 적어주세요.
      placeholder: (예) iPhone 11 Pro
    validations:
      required: false
  - type: dropdown
    id: p-select
    attributes:
      label: 어느 정도의 우선순의로 수정되면 좋겠는지 선택해 주세요.
      options:
        - p-1 (낮음)
        - p-2 (중간)
        - p-3 (중요)
        - p-4 (긴급)
    validations:
      required: true
  - type: textarea
    id: p-reason
    attributes:
      label: 우선순위 선정 이유
      description: 위에서 고르신 우선순위의 이유를 간략히 알려주세요.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        # 이슈를 제출해주셔서 감사합니다❤️
